export const pageData = {
  home: {
    path: '/',
    image: '/profile.png',
    alt: 'Alt text',
    title: 'Home | Temp Suscip',
    description: 'Learn more about lessons or sign-up today',
  },
  about: {
    path: '/about',
    image: '/profile.png',
    alt: 'Alt text',
    title: 'About | Temp Suscip',
    description: 'About lessons, reviews, and policy',
  },
  policy: {
    path: '/policy',
    image: '/profile.png',
    alt: 'Alt text',
    title: 'Policy | Temp Suscip',
    description: 'Studio policy',
  },
  blog: {
    path: '/blog',
    image: '/profile.png',
    alt: 'Alt text',
    title: 'Blog | Temp Suscip',
    description: 'Blog posts',
  },
  contact: {
    index: {
      path: '/contact',
      image: '/profile.png',
      alt: 'Alt text',
      title: 'Contact | Temp Suscip',
      description: 'Contact forms for handling emails',
    },
    nodemailer: {
      path: '/contact/nodemailer',
      image: '/profile.png',
      alt: 'Alt text',
      title: 'Contact | Temp Suscip',
      description: 'Nodemailer contact form',
    },
    sendgrid: {
      path: '/contact/sendgrid',
      image: '/profile.png',
      alt: 'Alt text',
      title: 'Contact | Temp Suscip',
      description: 'Sendgrid contact form',
    },
  },
  signUp: {
    index: {
      path: '/sign-up',
      image: '/profile.png',
      alt: 'Alt text',
      title: 'Sign Up | Temp Suscip',
      description: 'Information regarding schedule and availability',
    },
    calendly: {
      path: '/sign-up/calendly',
      image: '/profile.png',
      alt: 'Alt text',
      title: 'Sign Up | Temp Suscip',
      description: 'Calendly widget',
    },
    calcom: {
      path: '/sign-up/calcom',
      image: '/profile.png',
      alt: 'Alt text',
      title: 'Sign Up | Temp Suscip',
      description: 'Cal.com link',
    },
  },
};